"""added status column

Revision ID: a5ab4b04f9e1
Revises: 75baa005fa2c
Create Date: 2025-05-30 02:47:48.250698

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5ab4b04f9e1'
down_revision: Union[str, None] = '75baa005fa2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('complaint', sa.Column('status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('complaint', 'status')
    # ### end Alembic commands ###
